- hosts: java
  become: yes
  become_method: sudo

  tasks:
    - name: donwload java package to all node
      get_url: url=http://192.168.8.184/jdk-8u71-linux-x64.rpm dest=/opt

    - name: install package to all node
      yum: name=/opt/jdk-8u71-linux-x64.rpm state=installed

    - name: create a file
      file: path=/etc/profile.d/java.sh state=touch mode=0755

    - name: edit profile file
      lineinfile: dest=/etc/profile.d/java.sh line="{{ item }}"
      with_items:
        - JAVA_HOME=/usr/java/default
        - PATH=$PATH:$JAVA_HOME/bin
        - CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
        - export PATH
        - export JAVA_HOME
        - export CLASSPATH

    - name: reload the file
      shell: source /etc/profile.d/java.sh

    - name : debug value
      shell: echo "$JAVA_HOME"
      register: dist

    - debug: msg="{{ dist.stdout }}"

      
