- hosts: nn_host
  remote_user: root
  vars:
    NN_DATA_DIR: /var/data/hadoop/hdfs/nn

  tasks:
    - name: Creating HDFS data Directories
      file: path={{ NN_DATA_DIR }} state=directory owner=hdfs group=hadoop mode=775
    
    - name: Formatting the Namenode
      shell: su - hdfs -c '/usr/local/hadoop/bin/hdfs namenode -format'

    - name: copying namenode script
      copy: src=hadoop-namenode dest=/etc/init.d/ mode=755

    - name: copying zkfc script
      copy: src=hadoop-namenode dest=/etc/init.d/ mode=755

    - name: startup on
      shell: chkconfig hadoop-namenode on

    - name: start service
      shell: service hadoop-namenode start 

    - name: Formatting the Zookeeper Failover Controller
      shell: su - hdfs -c '/usr/local/hadoop/bin/hdfs zkfc-formatZK'

    - name: copying zkfc script
      copy: src=hadoop-zkfc dest=/etc/init.d/ mode=755

    - name: startup on
      shell: chkconfig hadoop-zkfc on

    - name: start service
      shell: service hadoop-zkfc start
      
